# Generated by Django 5.2.1 on 2026-10-08 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='nom',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
