# Generated by Django 5.2.1 on 2026-10-08 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_paymentmethod_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
